export interface LocationArtist {
  name: string;
  role: string;
  location: string;
  image: string;
  query: string;
  badge?: string;
}

export interface MusicRegionScene {
  id: string;
  name: string;
  state: string;
  flag: string;
  language: string;
  sceneTitle: string;
  sceneDesc: string;
  radioQuery: string;
  gradient: string;
  artists: LocationArtist[];
}

export const LOCATION_MUSIC_SCENES: MusicRegionScene[] = [
  {
    id: 'kerala',
    name: 'Kerala',
    state: 'Kerala, India',
    flag: '🌴',
    language: 'Malayalam',
    sceneTitle: 'Mollywood Indie & Cinematic Wave',
    sceneDesc: 'Kochi late night acoustic jams, Sushin Shyam hip-hop drops, Rex Vijayan alt-rock, and Dabzee Malabar street anthems.',
    radioQuery: 'Malayalam top hit songs Sushin Shyam Rex Vijayan official audio',
    gradient: 'from-emerald-700 via-teal-800 to-stone-900',
    artists: [
      {
        name: 'Sushin Shyam',
        role: 'Mollywood Sonic Architect',
        location: 'Kochi, Kerala',
        image: 'https://yt3.ggpht.com/YC3j2_0348PXH1IM5EDxAdYpvUlRxDU3EmCecPsfa5kahcWeBdZYsdZWTEx3mmSmJwQSd9UhTg=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Sushin Shyam hits official audio',
        badge: 'Aavesham • Manjummel Boys',
      },
      {
        name: 'Rex Vijayan',
        role: 'Kerala Indie & Rock Pioneer',
        location: 'Kollam, Kerala',
        image: 'https://img.youtube.com/vi/HUAAYwtusLI/hqdefault.jpg',
        query: 'Rex Vijayan songs official audio',
        badge: 'Avial • Kumbalangi',
      },
      {
        name: 'Jakes Bejoy',
        role: 'High-Impact Cinema Beats',
        location: 'Thrissur, Kerala',
        image: 'https://img.youtube.com/vi/CKpbdCciELk/hqdefault.jpg',
        query: 'Jakes Bejoy songs official audio',
        badge: 'RDX • King of Kotha',
      },
      {
        name: 'Dabzee',
        role: 'Malabar Hip-Hop & Folk Trap',
        location: 'Malappuram, Kerala',
        image: 'https://img.youtube.com/vi/3wDiqlTNlfQ/hqdefault.jpg',
        query: 'Dabzee songs official audio',
        badge: 'Manakkale Pattan',
      },
      {
        name: 'Sithara Krishnakumar',
        role: 'Soulful Folk & Classical Voice',
        location: 'Kozhikode, Kerala',
        image: 'https://yt3.ggpht.com/PgINZNe0qVxgMSXKG5vF82bNN4WCC12zgWsz9I7OLs4CLF9Cn0Vxq7Xc1ToupnzXrCv0nKfe3VM=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Sithara Krishnakumar best songs official audio',
        badge: 'Project Malabaricus',
      },
      {
        name: 'Hanan Shaah',
        role: 'Modern Acoustic & Melodies',
        location: 'Kerala, India',
        image: 'https://img.youtube.com/vi/6RdS6wLu7RY/hqdefault.jpg',
        query: 'Hanan Shaah songs official audio',
        badge: 'Neela Nilave',
      },
    ],
  },
  {
    id: 'tamilnadu',
    name: 'Tamil Nadu',
    state: 'Tamil Nadu, India',
    flag: '⚡',
    language: 'Tamil',
    sceneTitle: 'Chennai Kollywood Beats HQ',
    sceneDesc: 'Rockstar Anirudh high-octane bass, AR Rahman timeless orchestral masterworks, Yuvan late-night soul, and SaNa folk funk.',
    radioQuery: 'Tamil superhit songs Anirudh AR Rahman official audio',
    gradient: 'from-amber-600 via-orange-800 to-neutral-900',
    artists: [
      {
        name: 'Anirudh Ravichander',
        role: 'The Rockstar Hitmaker',
        location: 'Chennai, Tamil Nadu',
        image: 'https://yt3.ggpht.com/Tyx1R_RCijQJcBOOJEDqubRkpH0CYKeb_8KfxY_KCrGVktmwkB9yXYgQmwXySThHppPycR75=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Anirudh Ravichander hits official audio',
        badge: 'Leo • Jailer • Devara',
      },
      {
        name: 'A.R. Rahman',
        role: 'Mozart of Madras',
        location: 'Chennai, Tamil Nadu',
        image: 'https://yt3.ggpht.com/n6Yg9_f3l1q03JdK05l1JdM4-c0yS1m1P3zL=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'A.R. Rahman hits official audio',
        badge: 'Academy Award Winner',
      },
      {
        name: 'Yuvan Shankar Raja',
        role: 'The BGM & Melody Magician',
        location: 'Chennai, Tamil Nadu',
        image: 'https://img.youtube.com/vi/3wDiqlTNlfQ/hqdefault.jpg',
        query: 'Yuvan Shankar Raja hits official audio',
        badge: 'U1 Drugs • GOAT',
      },
      {
        name: 'Santhosh Narayanan',
        role: 'Raw Acoustic & Street Brass',
        location: 'Tiruchirappalli, Tamil Nadu',
        image: 'https://img.youtube.com/vi/cl0a3i2wFcc/hqdefault.jpg',
        query: 'Santhosh Narayanan songs official audio',
        badge: 'SaNa • Jigarthanda',
      },
      {
        name: 'Sid Sriram',
        role: 'Soulful Carnatic / Pop Fusion',
        location: 'Chennai, Tamil Nadu',
        image: 'https://yt3.ggpht.com/c1h5a_j9rG_3=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Sid Sriram Tamil hits official audio',
        badge: 'Maruvaarthai • Kannaana',
      },
    ],
  },
  {
    id: 'andhra_telangana',
    name: 'Andhra & Telangana',
    state: 'Andhra Pradesh & Telangana',
    flag: '🔥',
    language: 'Telugu',
    sceneTitle: 'Hyderabad Tollywood Mass Central',
    sceneDesc: 'Devi Sri Prasad (DSP) dance euphoria, Thaman S electronic rhythm, and heart-touching commercial blockbusters.',
    radioQuery: 'Telugu superhit songs DSP Thaman Sid Sriram official audio',
    gradient: 'from-red-600 via-rose-800 to-black',
    artists: [
      {
        name: 'Devi Sri Prasad (DSP)',
        role: 'Tollywood Mass Energy King',
        location: 'Hyderabad, Telangana',
        image: 'https://yt3.ggpht.com/ytc/AIdro_kA66CGEVLVE0h0YpG7iU87PR2QCQcKwFC6pnD_Xk7_pRo=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Devi Sri Prasad songs official audio',
        badge: 'Pushpa • Waltair Veerayya',
      },
      {
        name: 'Thaman S',
        role: 'Modern Commercial Beat Master',
        location: 'Hyderabad, Telangana',
        image: 'https://img.youtube.com/vi/CKpbdCciELk/hqdefault.jpg',
        query: 'Thaman S Telugu hits official audio',
        badge: 'Ala Vaikunthapurramuloo',
      },
      {
        name: 'Anurag Kulkarni',
        role: 'Vibrant Playback Vocalist',
        location: 'Kamareddy, Telangana',
        image: 'https://img.youtube.com/vi/HUAAYwtusLI/hqdefault.jpg',
        query: 'Anurag Kulkarni songs official audio',
        badge: 'Ramuloo Ramulaa',
      },
      {
        name: 'Ram Miriyala',
        role: 'Folk Pop & Indie Revolution',
        location: 'Guntur, Andhra Pradesh',
        image: 'https://img.youtube.com/vi/3wDiqlTNlfQ/hqdefault.jpg',
        query: 'Ram Miriyala songs official audio',
        badge: 'Tillu Square • Chitti',
      },
      {
        name: 'Mangli',
        role: 'Dynamic Folk Vocal Power',
        location: 'Anantapur, Andhra Pradesh',
        image: 'https://img.youtube.com/vi/cl0a3i2wFcc/hqdefault.jpg',
        query: 'Mangli songs official audio',
        badge: 'Saranga Dariya',
      },
    ],
  },
  {
    id: 'mumbai_north',
    name: 'Mumbai & North',
    state: 'Maharashtra / North India',
    flag: '🌙',
    language: 'Hindi',
    sceneTitle: 'Bollywood Melodies & Late Night Soul',
    sceneDesc: 'Arijit Singh soulful acoustic confessions, Pritam chartbusters, Shreya Ghoshal golden tone, and cinematic Hindi romance.',
    radioQuery: 'Bollywood romantic soulful hits Arijit Singh Pritam official audio',
    gradient: 'from-indigo-700 via-purple-900 to-neutral-950',
    artists: [
      {
        name: 'Arijit Singh',
        role: 'Bollywood Soul King',
        location: 'Mumbai, Maharashtra',
        image: 'https://yt3.ggpht.com/DcEzZrPCQRSSs47rMbdJ3UJkQUCN3X8SKf8aCnvOgd2BmPihAz-0jBGJgEVh9_P8EiSBVNyixDs=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Arijit Singh hits official audio',
        badge: 'Kesariya • Chaleya',
      },
      {
        name: 'Pritam',
        role: 'The Master Melody Architect',
        location: 'Mumbai, Maharashtra',
        image: 'https://img.youtube.com/vi/6RdS6wLu7RY/hqdefault.jpg',
        query: 'Pritam songs official audio',
        badge: 'Brahmastra • YJHD',
      },
      {
        name: 'Shreya Ghoshal',
        role: 'The Golden Melody Queen',
        location: 'Mumbai, Maharashtra',
        image: 'https://yt3.ggpht.com/PgINZNe0qVxgMSXKG5vF82bNN4WCC12zgWsz9I7OLs4CLF9Cn0Vxq7Xc1ToupnzXrCv0nKfe3VM=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Shreya Ghoshal songs official audio',
        badge: 'Param Sundari • Deewani',
      },
      {
        name: 'Sachin-Jigar',
        role: 'Electronic Folk & Melodies',
        location: 'Mumbai, Maharashtra',
        image: 'https://img.youtube.com/vi/HUAAYwtusLI/hqdefault.jpg',
        query: 'Sachin Jigar songs official audio',
        badge: 'Stree 2 • Bhediya',
      },
      {
        name: 'Jasleen Royal',
        role: 'Acoustic Indie & Indie Pop',
        location: 'Ludhiana / Mumbai',
        image: 'https://img.youtube.com/vi/fHI8X4OXluQ/hqdefault.jpg',
        query: 'Jasleen Royal songs official audio',
        badge: 'Heeriye • Din Shagna',
      },
    ],
  },
  {
    id: 'punjab',
    name: 'Punjab',
    state: 'Punjab, India',
    flag: '💥',
    language: 'Punjabi',
    sceneTitle: 'Punjabi Trap & Desi Street Wave',
    sceneDesc: 'Heavy 808 sub-bass, street anthems, and international Punjabi chart-toppers dominating global streaming.',
    radioQuery: 'Punjabi hip hop trap hits Diljit Dosanjh Karan Aujla official audio',
    gradient: 'from-red-600 via-orange-800 to-stone-900',
    artists: [
      {
        name: 'Diljit Dosanjh',
        role: 'Global Desi Icon',
        location: 'Dosanjh Kalan, Punjab',
        image: 'https://yt3.ggpht.com/V_M1bC=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Diljit Dosanjh hits official audio',
        badge: 'G.O.A.T. • Lover • Coachella',
      },
      {
        name: 'Karan Aujla',
        role: 'Punjabi Trap & Wave',
        location: 'Ghurala, Punjab',
        image: 'https://yt3.ggpht.com/Da4zbrS4XLxzb3xVNT14aKr22aBg1blJCuCBppbYglO_uDmElYopgoDk7XV6UWNxthI96XOYrw=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'Karan Aujla songs official audio',
        badge: 'Softly • Tauba Tauba',
      },
      {
        name: 'AP Dhillon',
        role: 'Synth-Pop & Punjabi Trap',
        location: 'Gurdaspur, Punjab',
        image: 'https://img.youtube.com/vi/cl0a3i2wFcc/hqdefault.jpg',
        query: 'AP Dhillon hits official audio',
        badge: 'Brown Munde • Excuses',
      },
      {
        name: 'Shubh',
        role: 'Melodic Street Trap',
        location: 'Punjab, India',
        image: 'https://img.youtube.com/vi/3wDiqlTNlfQ/hqdefault.jpg',
        query: 'Shubh songs official audio',
        badge: 'Cheques • Still Rollin',
      },
      {
        name: 'Sidhu Moose Wala',
        role: 'The Immortal Legend',
        location: 'Moosa, Mansa, Punjab',
        image: 'https://img.youtube.com/vi/6RdS6wLu7RY/hqdefault.jpg',
        query: 'Sidhu Moose Wala hits official audio',
        badge: '295 • The Last Ride',
      },
    ],
  },
  {
    id: 'global',
    name: 'Global',
    state: 'International Hot 100',
    flag: '🌐',
    language: 'English / Pop',
    sceneTitle: 'Global Billboard Hot 100 Pulse',
    sceneDesc: 'Worldwide stream record-breakers and international pop, synthwave, and R&B legends.',
    radioQuery: 'Billboard Hot 100 top pop songs The Weeknd Bruno Mars official audio',
    gradient: 'from-blue-700 via-indigo-900 to-black',
    artists: [
      {
        name: 'The Weeknd',
        role: 'Global R&B / Pop Icon',
        location: 'Toronto, Canada',
        image: 'https://yt3.ggpht.com/grVR2wV20AdBLDkCKENTVTGci92l7ZB6hSr0B2huHrrqYDVNs_eVD9qN0JvOCTKbney97vqaRQ=s800-c-k-c0xffffffff-no-rj-mo',
        query: 'The Weeknd hits official audio',
        badge: 'Blinding Lights • Starboy',
      },
      {
        name: 'Bruno Mars',
        role: 'Funk & Soul Mastermind',
        location: 'Honolulu, Hawaii, USA',
        image: 'https://img.youtube.com/vi/fHI8X4OXluQ/hqdefault.jpg',
        query: 'Bruno Mars hits official audio',
        badge: 'Die With A Smile • 24K',
      },
      {
        name: 'Taylor Swift',
        role: 'Pop & Storytelling Titan',
        location: 'Nashville, USA',
        image: 'https://img.youtube.com/vi/3wDiqlTNlfQ/hqdefault.jpg',
        query: 'Taylor Swift hits official audio',
        badge: 'Cruel Summer • Anti-Hero',
      },
      {
        name: 'Billie Eilish',
        role: 'Alternative Pop Visionary',
        location: 'Los Angeles, USA',
        image: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
        query: 'Billie Eilish hits official audio',
        badge: 'Birds of a Feather',
      },
    ],
  },
];
